main/urls.py
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
	path("", views.homepage, name="homepage"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from main.views import LoginView, LogoutView

urlpatterns = [
	path("", include("main.urls")),
    path('admin/', admin.site.urls),
    # path('api/v1/auth/login/', LoginView.as_view()),
    # path('api/v1/auth/login/', LoginView.as_view()),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.utils import timezone

class Post(models.Model):
	title = models.CharField(max_length=200)
	summary = models.CharField(max_length=200)

	image = models.ImageField(default='default.jpg', upload_to='post_img')
	date_created = models.DateTimeField(auto_now_add=True, db_index=True)

	def __str__(self):
		return self.title

class Opportunities(models.Model):
	title= models.CharField(max_length=200)
	summary = models.CharField(max_length=200)

	image = models.ImageField(default='default.jpg', upload_to='opp_img')

	def __str__(self):
		return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ["username", "email", "password1", "password2"]

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Opportunities
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm

# Create your views here.

def homepage(request):
	return render(request=request,
				  template_name="main/home.html",
				  context={"post": Post.objects.order_by('-date_created')[0], "opps":Opportunities.objects.all()}
	)


def register(request):
	if request.method == "POST" :
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"New Account created : {username}")
			login(request, user)
			return redirect("main:homepage")
		else:
			for msg in form.error_messages:
				messages.error(request, f"{msg} : {form.error_messages[msg]}")

	form = NewUserForm
	return render(request,
				  "main/register.html",
				  {"form": form})

def logout_request(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("main:homepage")

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"Logged in as {username}")
				return redirect("main:homepage")
			else:
				messages.error(request, "Invalid username or password")
		else:
			messages.error(request, "Invalid username or password")


	form = AuthenticationForm()
	return render(request,
				  "main/login.html",
				  {"form": form})




main/templates/main/header.html
<head>
	{% load static %}
		<!-- Bootstrap CSS -->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
	<header class="site-header">
		{% include "main/includes/navbar.html" %}
	</header>

	<main role="main" class="container">
		<div class="row">			
			{% block content %}
			{% endblock %}
		</div>
		
	</main>
	<!--Bottom Footer-->
		<div class="bottom section-padding">
			<div class="container">
				<div class="row">
					<div class="col-md-12 text-center">
						<div class="copyright">
							<p>© <span>2019</span> <a href="#" class="transition">My Django Site</a> All rights reserved.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
<!--Bottom Footer-->

</body>


main/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}
	
		{% if user.is_authenticated %}
			{% include "main/includes/sidebar.html" %}
		{% endif %}		

			<div class="col-8">
				<br>
				{% include "main/includes/messages.html" %}
				{% include "main/posts.html" with posts=posts %}
			</div>

{% endblock %}

main/templates/main/includes/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
	{{ message }}
</div>
{% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">MySite</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarText">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Features</a>
					</li>
				</ul>
				<ul class="navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="/Profile"><span class="fa fa-user-circle"></span> {{ user.username }}</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/logout"><span class="fa fa-sign-in"></span> Logout</a>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="/register"><span class="fa fa-user"></span> Sign Up</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/login"><span class="fa fa-sign-in"></span> Login</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>

main/templates/main/includes/sidebar.html
		

			<div class="col-4">
			<br>
			<div class="card text-white bg-dark mb-3">
				<div class="card-body">
				<h6>COMPLETE YOUR PROFILE <span style="float: right;">EARN $</span></h6>
				
				<div class="progress">
					<div class="progress-bar" role="progressbar" style="width: 10%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
					
				</div>
				<small>
						progress : 10%
				</small>
				</div>
			</div>
			</div>
		

main/templates/main/login.html
{% extends "main/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section m-4">	
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Enter your details to login
				</legend>
					{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Log In</button>
			</div>
		</form>

		<div class="border-top pt-3">
			<small class="text-muted">
				Don't have an account, <a href="{% url 'main:register' %}">Sign Up</a> instead
			</small>
		</div>
	</div>
{% endblock %}

main/templates/main/posts.html
{% block content %}
	
	
	<!-- Background Image -->
	<div class="card bg-dark text-white mb-4">
		<img src="{{ post.image.url }}" class="card-img" style="height: 21rem; object-fit: cover;">
		
		<!-- Text Overlay -->
		<div class="card-body d-flex flex-column card-img-overlay">
			<p class="card-text text-right">Featured</p>
			<h2 class="card-title">{{ post.title }}</h2>
			<p class="card-text">{{ post.summary }} </p>

			<div class="mt-auto">
				<a href="#" class="btn btn-light">Learn More</a>
			</div>
		</div>
	</div>
	<br>
	

	<p class="mb-0"><strong>Available Opportunites</strong></p>
	<div class="card-deck">
		{% for opp in opps %}
		<div class="card bg-dark text-white overlay-card mt-4">
			<img src="{{ opp.image.url }}" class="card-img" style="height: 18rem; object-fit: cover;">
			<div class="card-img-overlay">
				<h4 class="card-title">{{ opp.title }}</h4>
				<p class="card-text">{{ opp.summary}}</p>
				<a href="#" class="btn btn-success">Learn more</a>
			</div>
		</div>
		{% if forloop.counter|divisibleby:"2"  %}
            </div><div class="card-deck">
        {% endif %}
		{% endfor %}
	</div>

</div>


{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section m-4">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'main:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}